[package]
name = "imlob"
version = "0.1.0"
edition = "2021"
default-run = "imlob"

[dependencies]
crossterm = "0.27"
ratatui = { version = "0.26", features = ["all-widgets"] }
rand = "0.8"

[[bench]]
name = "orderbook_bench"
harness = false
